Repository PrinceHard/CardioRed, pull requests merged in 2022-05, with the labels that each got.

#4 Feature/create domain medico
  backend/cardio/pom.xml
  backend/cardio/src/main/java/com/cardiored/cardio/domain/Docente.java
  backend/cardio/src/main/java/com/cardiored/cardio/domain/DoctorType.java
  backend/cardio/src/main/java/com/cardiored/cardio/domain/Medico.java
  backend/cardio/src/main/java/com/cardiored/cardio/domain/Residente.java
  backend/cardio/src/main/java/com/cardiored/cardio/domain/Titulation.java
Labels: enhancement

#16 Medico repositories created
  backend/cardio/src/main/java/com/cardiored/cardio/repository/DocenteRepository.java
  backend/cardio/src/main/java/com/cardiored/cardio/repository/MedicoRepository.java
  backend/cardio/src/main/java/com/cardiored/cardio/repository/ResidenteRepository.java
Labels: enhancement

#18 Created PacienteRepository
  backend/cardio/src/main/java/com/cardiored/cardio/repository/PacienteRepository.java
Labels: enhancement

#20 created paciente and user services
  backend/cardio/src/main/java/com/cardiored/cardio/controller/PacienteController.java
  backend/cardio/src/main/java/com/cardiored/cardio/repository/PacienteRepository.java
  backend/cardio/src/main/java/com/cardiored/cardio/repository/UserRepository.java
  backend/cardio/src/main/java/com/cardiored/cardio/service/PacienteService.java
  backend/cardio/src/main/java/com/cardiored/cardio/service/UserService.java
Labels: enhancement

#21 Feature/create service medico
  backend/cardio/src/main/java/com/cardiored/cardio/domain/DoctorType.java
  backend/cardio/src/main/java/com/cardiored/cardio/domain/Titulation.java
  backend/cardio/src/main/java/com/cardiored/cardio/service/DocenteService.java
  backend/cardio/src/main/java/com/cardiored/cardio/service/MedicoService.java
  backend/cardio/src/main/java/com/cardiored/cardio/service/ResidenteService.java
Labels: enhancement

#25 Feature/create controller medico
  backend/cardio/src/main/java/com/cardiored/cardio/controller/DocenteController.java
  backend/cardio/src/main/java/com/cardiored/cardio/controller/MedicoController.java
  backend/cardio/src/main/java/com/cardiored/cardio/controller/ResidenteController.java
Labels: Implementation

#29 Feature/create login page
  frontend/src/App.js
  frontend/src/assets/img-login.svg
  frontend/src/assets/logo.svg
  frontend/src/components/LoginContainer.css
  frontend/src/components/LoginContainer.js
  frontend/src/index.html
  frontend/src/index.js
  frontend/src/pages/Login.js
  frontend/webpack.config.js
Labels: Implementation

#37 Feature/create navbar
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/assets/logo-navbar.svg
  frontend/src/components/Login/LoginContainer.css
  frontend/src/components/Login/LoginContainer.js
  frontend/src/components/Navbar/navbar.js
  frontend/src/components/Navbar/style.css
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/pages/Home.js
  frontend/src/pages/Login.js
  frontend/webpack.config.js
Labels: Implementation

#36 Feature/create paciente page
  frontend/src/components/CounterElements.js
  frontend/src/components/FormSearch.js
  frontend/src/components/Pagination.js
  frontend/src/pages/PacientePage.js
Labels: Implementation

#38 Feature/home page
  frontend/src/assets/coracao.svg
  frontend/src/assets/coracao2.svg
  frontend/src/assets/github.svg
  frontend/src/components/Footer/footer.js
  frontend/src/components/Footer/style.css
  frontend/src/components/HomePage/HomeContent.js
  frontend/src/components/HomePage/style.css
  frontend/src/components/Navbar/navbar.js
  frontend/src/components/Navbar/style.css
  frontend/src/index.css
  frontend/src/pages/Home.js
Labels: enhancement

#40 Fix/fixing paciente page
  frontend/src/App.js
  frontend/src/components/Login/LoginContainer.css
  frontend/src/components/PacientesTable/table.css
  frontend/src/components/PacientesTable/table.js
  frontend/src/components/SearchBar/FormSearch.css
  frontend/src/components/SearchBar/FormSearch.js
  frontend/src/pages/Pacientes.js
Labels: bug

#41 Feature/paciente crud
  frontend/src/App.js
  frontend/src/components/FormPaciente/FormPaciente.js
  frontend/src/components/Modal/CreateAndUpdate/ModalCreateAndUpdate.css
  frontend/src/components/Modal/CreateAndUpdate/ModalCreateAndUpdate.js
  frontend/src/components/Modal/Delete/ModalDelete.css
  frontend/src/components/Modal/Delete/ModalDelete.js
  frontend/src/components/Modal/View/ModalView.js
  frontend/src/components/Navbar/navbar.js
  frontend/src/components/PacientesTable/table.js
  frontend/src/components/Paginator/Pagination.js
  frontend/src/components/registerButton/register.js
  frontend/src/pages/Pacientes.js
Labels: enhancement

#45 Feature/medico crud
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Form/FormMedico/FormMedico.js
  frontend/src/components/Form/FormPaciente/FormPaciente.js
  frontend/src/components/MedicosTable/table.js
  frontend/src/components/Modal/CreateAndUpdate/ModalCreateAndUpdate.js
  frontend/src/components/PacientesTable/table.js
  frontend/src/pages/Medicos.js
  frontend/src/pages/Pacientes.js
Labels: enhancement

#50 Feature/validate paciente forms
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Form/FormPaciente/Create/FormCreatePaciente.css
  frontend/src/components/Form/FormPaciente/Create/FormCreatePaciente.js
  frontend/src/components/Form/FormPaciente/Update/FormUpdatePaciente.js
  frontend/src/components/Form/FormPaciente/View/FormViewPaciente.js
  frontend/src/components/Modal/Create/ModalCreate.js
  frontend/src/components/Modal/Delete/ModalDelete.js
  frontend/src/components/Modal/Update/ModalUpdate.js
  frontend/src/components/Modal/View/ModalView.js
  frontend/src/components/PacientesTable/table.css
  frontend/src/components/PacientesTable/table.js
  frontend/src/components/Paginator/Paginator.js
  frontend/src/components/SearchBar/FormSearch.js
  frontend/src/pages/Pacientes.js
Labels: enhancement

#52 Feature/create authorization front end
  backend/cardio/src/main/java/com/cardiored/cardio/util/TokenCreator.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Login/LoginContainer.js
  frontend/src/components/PacientesTable/table.js
  frontend/src/components/Paginator/Paginator.js
  frontend/src/pages/Home.js
  frontend/src/pages/Pacientes.js
  frontend/src/utils/authToken.js
  frontend/src/utils/userAuth.js
Labels: enhancement
